preload = ~/my_dot_files/background_images/ultrawide/hades2.png

wallpaper {
    monitor = DP-1
    path = ~/my_dot_files/background_images/ultrawide/hades2.png
    fit_mode = fill
}

splash = false

